language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
  - "pypy"
  - "pypy3"
# command to install dependencies
install:
  - python ./setup.py install

# command to run tests
script:
  - python -m unittest discover fbchat_archive_parser/testing
